version: '3.4'

name: demo1

services:
  minimalservice:
    image: ${DOCKER_REGISTRY-}minimalservice
    build:
      context: .
      dockerfile: src/MinimalService/Dockerfile
    networks:
      network:
        ipv4_address: 172.21.1.2

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24